export default {
	ch: "switzerland",
	cz: "czech republic",
	at: "austria",
	ie: "ireland",
	gr: "greece",
	nl: "netherlands",
	pt: "portugal",
	no: "norway",
	lv: "latvia",
	lt: "lithuania",
	it: "italy",
	ro: "romania",
	pl: "poland",
	be: "belgium",
	fr: "france",
	bg: "bulgaria",
	de: "germany",
	hu: "hungary",
	sk: "slovakia",
	si: "slovenia",
	se: "sweden",
	gb: "united kingdom",
	nz: "new zealand",
	au: "australia",
	eg: "egypt",
	za: "south africa",
	ma: "morocco",
	cn: "china",
	in: "india",
	id: "indonesia",
	ru: "russia",
	tw: "taiwan",
	tr: "turkey",
	th: "thailand",
	ph: "philippines",
	ua: "ukraine",
	jp: "japan",
	hk: "hong kong",
	sg: "singapore",
	kr: "korea",
	ca: "canada",
	cu: "cuba",
	us: "united states",
	mx: "mexico",
	co: "colombia",
	ve: "venezuela",
	ar: "argentina",
	br: "brazil",
	il: "israel",
	ae: "united arab emirates",
	sa: "saudi arabia"
}